### ISSUE TITLE
Bool Tool error 

### ISSUE THREAD

**Issue by bcompositor** [nickberckley/bool_tool#36] opened 2024-12-24 12:21 UTC
I've been testing this tool and it does not seem to be operational. 
Upon installing the extension in 4.4.0 alpha (hash: 2c9ab532732d) on Linux I get the following error: 
bpy.ops.object.carve(shape='CIRCLE')
Python: RuntimeError: could not create instance of OBJECT_OT_carve to call callback function 'invoke'

Any clues?

**Comment by nickberckley** [comment] 2024-12-24 12:27
This is a duplicate of #33 
Blender 4.4 isn't supported yet, and the bug seems to be from the Blender side. When it's in the beta stage I'll investigate and support it.

**Closed by nickberckley** 2024-12-24 12:27 UTC

**Comment by bcompositor** [comment] 2024-12-24 12:29
Oh, my bad! Many thanx 4 the prompt reply, hope it gets fixed one day cause it looks like really promising! :) 
Happy Xmas.
